import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import MainFooter from '@/components/Footer'
import CustomProvider from '@/Redux/Prvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
        <Navbar/>
        {children}
        <MainFooter/>
        </CustomProvider>
       
        </body>
    </html>
  )
}
